services:
  - type: web
    name: niko-robin-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: PORT
        value: 3000
      - key: DISCORD_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: GUILD_ID
        sync: false
      - key: TICKET_CATEGORY_ID
        sync: false
      - key: SUPPORT_ROLE_ID
        sync: false
      - key: AUTO_ROLE_ID
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
